export const FETCH_CITIES = "FETCH_CITIES";
export const DELETE_CITY = "DELETE_CITY";

export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

export const FETCH_ITINERARIES = "FETCH_ITINERARIES";
export const DELETE_ITINERARY = "DELETE_ITINERARY";
export const FETCH_ITINERARIES_ID = "FETCH_ITINERARIES_ID";
export const FETCH_ITINERARIES_HASHTAG = "FETCH_ITINERARIES_HASHTAG";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const POST_COMMENTS = "POST_COMMENTS";

export const POST_FAVORITES = "POST_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";

export const GET_ERRORS = "GET_ERRORS";

export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
